### ISSUE TITLE
MemSQL Ops is currently disabled because it is out of disk space.

### ISSUE THREAD

**Issue by scottrobertson** [memsql/memsql-docker-quickstart#12]
Trying to run this on CircleCI, and i am getting the following error, when running:

```
sudo docker run -p 3306:3306 -v /memsql:/memsql memsql/quickstart
```

```
MemSQL Ops is running with pid 39
The web UI is running on port 9000
MemSQL Ops is currently disabled because it is out of disk space.
```

**Comment by carlsverre** [comment]
1. Did you initialize /memsql using the command in the Readme?  If not you should use Docker volumes (remove the `/` prefix on the host side so its just `-v memsql:/memsql`)
2. Is any disk on the machine empty or close to being empty?

**Comment by scottrobertson** [comment]
@carlsverre hey

1) That was actually just a copy/paste fail. It fails without the "/" and also without any volume attached at all. 

2) ~50gb available when i run: `sudo docker run memsql/quickstart df /` and on the host machine.

**Comment by carlsverre** [comment]
Ops checks the Ops data directory (which will be in the memsql volume) and the temporary directory in the container.  Can you check that `/tmp` has space in the container?  Try setting the TMPDIR environment variable to a location in the container (or a mounted volume) that has free space.

**Comment by scottrobertson** [comment]
@carlsverre /tmp has the same amount of disk space available.

**Comment by scottrobertson** [comment]
it's worth noting that `/memsql-ops` is not listed in the `VOLUMES` in the Dockerfile. Not sure if that makes a difference.

Just find it odd that this works locally totally fine.

**Comment by scottrobertson** [comment]
And to confirm, setting TMPDIR does not fix it.

**Comment by carlsverre** [comment]
Can you get the full log from memsql-ops after it fails?  The log is at `/var/lib/memsql-ops/memsql-ops.log`.  When it hits that error it prints out a more descriptive error that includes exactly what issue it is seeing on which path.
