### ISSUE TITLE
Unable to create a new schema

### ISSUE THREAD

**Issue by idkw** [memsql/memsql-docker-quickstart#20]
Hello,

I started the container with the provider docker run command :
```docker run -d -p 3306:3306 -p 9000:9000 -v memsql:/memsql --name=memsql memsql/quickstart```

I then ran the memsql-shell container and tried creating a schema with : 
``` CREATE SCHEMA `new_schema` ; ```

It fails with the following error : 
`ERROR 1772 (HY000): CREATE PARTITION DATABASE for operation `CREATE DATABASE` failed with error 1026:Leaf Error (127.0.0.1:3307): Error writing file 'unknown (see tracelog)' (errno: 4)`

Here are the logs of the memsql container : 
[memsql.log](https://github.com/memsql/memsql-docker-quickstart/files/2555213/memsql.log)

What did I do wrong ?

Thank you

**Comment by carlsverre** [comment]
According to the log the leaf ran out of memory while creating the database:
```
382261827 2018-11-06 22:10:52.277   WARN: Failed to allocate 67108864 bytes of memory from kernel. Error 12: Cannot allocate memory
382261855 2018-11-06 22:10:52.277  ERROR: Out of memory allocating transaction buffer of size 64 MB.
```

Make sure you have enough memory available for MemSQL.  Note, if you are running docker on Windows or Mac, make sure you have increased the amount of memory available to the virtual machine.  To do this on Mac, check the advanced section of this guide: https://docs.docker.com/docker-for-mac/#advanced.  To do this on Windows, check out the advanced section of this guide: https://docs.docker.com/docker-for-windows/#advanced

MemSQL recommends a minimum of 4GB of memory to be available.
